spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/article-h2-db
    username: silva
    password: silva
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
